### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Damian2057** [Damian2057/TeleCom#2]
- [ ] Adding an option selection mechanic 
- [ ] interface / communication with the user 
- [ ] connection of classes to handle files  
- [ ] File encoding / decoding 
- [ ] checking the correctness of the program
